use DumDum;
Alter table TroopLevel add ConstTime int ;
UPDATE TroopLevel SET ConstTime = 700 WHERE TroopLevelId =1;
UPDATE TroopLevel SET ConstTime = 600 WHERE TroopLevelId =2;
UPDATE TroopLevel SET ConstTime = 500 WHERE TroopLevelId =3;
UPDATE TroopLevel SET ConstTime = 400 WHERE TroopLevelId =4;
UPDATE TroopLevel SET ConstTime = 300 WHERE TroopLevelId =5;
UPDATE TroopLevel SET ConstTime = 700 WHERE TroopLevelId =6;
UPDATE TroopLevel SET ConstTime = 600 WHERE TroopLevelId =7;
UPDATE TroopLevel SET ConstTime = 500 WHERE TroopLevelId =8;
UPDATE TroopLevel SET ConstTime = 400 WHERE TroopLevelId =9;
UPDATE TroopLevel SET ConstTime = 300 WHERE TroopLevelId =10;
UPDATE TroopLevel SET ConstTime = 700 WHERE TroopLevelId =11;
UPDATE TroopLevel SET ConstTime = 600 WHERE TroopLevelId =12;
UPDATE TroopLevel SET ConstTime = 500 WHERE TroopLevelId =13;
UPDATE TroopLevel SET ConstTime = 400 WHERE TroopLevelId =14;
UPDATE TroopLevel SET ConstTime = 300 WHERE TroopLevelId =15;
UPDATE TroopLevel SET ConstTime = 700 WHERE TroopLevelId =16;
UPDATE TroopLevel SET ConstTime = 600 WHERE TroopLevelId =17;
UPDATE TroopLevel SET ConstTime = 500 WHERE TroopLevelId =18;
UPDATE TroopLevel SET ConstTime = 400 WHERE TroopLevelId =19;
UPDATE TroopLevel SET ConstTime = 300 WHERE TroopLevelId =20;
UPDATE TroopLevel SET ConstTime = 700 WHERE TroopLevelId =21;
